adjust gradle.properties to seek for optimal working builds...
Some changes are required to get builds that do not crash in the middle
due to OOM:

```
Error: Exception in thread "Daemon client event forwarder" java.lang.OutOfMemoryError: Java heap space
ERROR: D8: java.lang.OutOfMemoryError: Java heap space
```

The daemon client should not need much memory space (unless the daemon
implementation is super lame), so remove daemon heap space specifier.